#!/usr/bin/env node
// Copies agent/ to build/agent/ (ignored by Git) and writes the vision relay
// settings from the repository-root .env into build/agent/config/vision.js.
// The key reaches Studio (项目「···」▸ 本地导入 → build/agent) and the glasses
// without ever being committed. The key itself is never printed.
//
//   npm run build:agent        # needs READOUBLE_VISION_KEY in .env
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

// Minimal .env reader: KEY=VALUE lines, optional quotes, # comments, `export` prefix.
export function parseEnv(text) {
  const env = {};
  for (const rawLine of String(text).split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith('#')) continue;
    const eq = line.indexOf('=');
    if (eq <= 0) continue;
    const key = line.slice(0, eq).trim().replace(/^export\s+/, '');
    let value = line.slice(eq + 1).trim();
    const quoted = value.length >= 2 &&
      ((value[0] === '"' && value.endsWith('"')) || (value[0] === "'" && value.endsWith("'")));
    if (quoted) value = value.slice(1, -1);
    env[key] = value;
  }
  return env;
}

export function mergeVisionConfig(base, env) {
  const key = (env.READOUBLE_VISION_KEY || '').trim();
  if (!key) throw new Error('READOUBLE_VISION_KEY is missing from .env');
  const merged = { ...base, apiKey: key };
  if (env.READOUBLE_VISION_BASE_URL) merged.baseUrl = env.READOUBLE_VISION_BASE_URL.trim();
  if (env.READOUBLE_VISION_MODEL) merged.model = env.READOUBLE_VISION_MODEL.trim();
  if (env.READOUBLE_VISION_EFFORT !== undefined) merged.reasoningEffort = env.READOUBLE_VISION_EFFORT.trim();
  return merged;
}

export function renderVisionConfig(config) {
  return '// Generated by tools/build_agent.mjs from .env. Never commit this file.\n' +
    'export default ' + JSON.stringify(config, null, 2) + ';\n';
}

async function main() {
  const envPath = path.join(ROOT, '.env');
  if (!fs.existsSync(envPath)) {
    throw new Error('.env not found: copy .env.example to .env and fill in READOUBLE_VISION_KEY');
  }
  const env = parseEnv(fs.readFileSync(envPath, 'utf8'));
  const baseUrl = pathToFileURL(path.join(ROOT, 'agent', 'config', 'vision.js')).href;
  const base = (await import(baseUrl)).default;
  const config = mergeVisionConfig(base, env);
  const out = path.join(ROOT, 'build', 'agent');
  fs.rmSync(out, { recursive: true, force: true });
  fs.cpSync(path.join(ROOT, 'agent'), out, { recursive: true });
  fs.writeFileSync(path.join(out, 'config', 'vision.js'), renderVisionConfig(config));
  console.log('wrote build/agent (model ' + config.model + ', effort ' +
    (config.reasoningEffort || '-') + ', key from .env)');
  console.log('Studio: 项目「···」▸ 本地导入 → 选择 build/agent → 上传云端');
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  main().catch((error) => {
    console.error('build:agent failed: ' + error.message);
    process.exit(1);
  });
}
